### ISSUE TITLE
Find commercial lawn care interviews

### ISSUE THREAD

**Issue by davidjevans** [MRSD2018/GroundsBot#26]
Find a company to interview, reach out, and set up at least 1 interview.

Here is mock email:

"Dear Mr. Shanley,

My name is Joe Phaneuf, and my colleagues and I are doing graduate research at Carnegie Mellon regarding the challenges of groundskeeping in [market].

We were wondering if you would be kind enough to take 15-20 minutes of your time to talk with us about your experiences with groundskeeping at [company]?

Thank you very much for your time.

Best regards,
-Joe”

**Comment by jdriscoll319** [comment]
Reached out to the following:
http://www.anlawnservice.com
https://lawnlove.com/
http://www.prolawncarecorp.com/index.html
