### ISSUE TITLE
Conduct highway department interview

### ISSUE THREAD

**Issue by davidjevans** [MRSD2018/GroundsBot#29]
Interview at least 1 person from market to understand goals and problems of groundskeeping in market.

In person interview is preferable, but over the phone works too.

**Comment by jphaneuf** [comment]
not enough personnel, can't add people, can hire temporary
focus is mainly on roads (paving, drainage, landscaping crew)
most mowing out on contract
spend ~ 1 million 
if want more mowing something has to give
not all of the municipalities , there's a misunderstanding of what the responsibilities are
in the burrows only responsible for certain parts, state is responsible
they do herbicide spraying

**Comment by jphaneuf** [comment]
comes down to balancing funding
allocated reasonably well
changed the way they did mowing this year, changed contract, partial mowing and then a full mow

**Comment by jphaneuf** [comment]
got a lot of complaints from that, was getting overgrown

**Comment by jphaneuf** [comment]
why can't we ask workers to pick up trash as well?

**Comment by jphaneuf** [comment]
would mow more just for aesthetics

**Comment by jphaneuf** [comment]
if you don't mow trees start to grow

**Comment by jphaneuf** [comment]
ramps/intersections there are sight distance issues

**Comment by jphaneuf** [comment]
doesn't have a lot of equipment, most of it put out to bid

**Comment by jphaneuf** [comment]
usually have a month to mow from a bid

**Comment by jphaneuf** [comment]
-send email to jason to get contractor names

**Comment by jphaneuf** [comment]
contract might say 'within 1 ft of trees' etc..., people go out to check specs

**Comment by jphaneuf** [comment]
large tractors with pull behind mower decks

**Comment by jphaneuf** [comment]
4-5 man crew on staff put in place in april w/ weedwackers, small tractor w/ mowing deck, go around and hit areas not on contract, large fields, react to complaints

**Comment by jphaneuf** [comment]
any kind of job on the road is in a dangerous job, in traffic, mowing , not on slopes where tractor can flip, use weed whacker instead, for the most part less dangerous than patching potholes

**Comment by jphaneuf** [comment]
automation: not yet, still low bid w/ contractors, was trying to find some equipment for picking up garbage, some state had some equipment to do that, cheapest most effective way is still people.  mowing is still in that area, not exploring that way.  don't want to limit a contractor's means or methods.  most creative contractors will win bid.  have seen some remote ones, but mostly just using big tractors.

**Comment by jphaneuf** [comment]
there's a push / awareness about green space and storm control, reducing impermeable pavement area, the challenge is maintenance of it.  maintenance budget hasn't changed in several years, with this push for green infrastructure, giving water a place to absorb into ground ,  anything penndot can do to help is useful, several storm water retention places which require maintenance.  who's going to do it, where's the money coming from?

**Comment by jphaneuf** [comment]
do a lot of beautification permits, folks paying for that and maintaining.  Tend to do just what they need to maintain safety,

**Comment by jphaneuf** [comment]
As PennDot increases green infrastructure, where does money come from?

**Comment by jphaneuf** [comment]
pittsburgh wet weather, 28 billion project to reduce runoff, FEMA? hasn't affected penndot yet

**Comment by jphaneuf** [comment]
south hills developed 1900s no sight at all into retention of storm water

**Comment by jphaneuf** [comment]
have to figure out a way to maintain that greenspace

**Comment by jphaneuf** [comment]
jason zang: jzang@pa.gov
