### ISSUE TITLE
Integration PCB needs Arduino USB. Mechanical conflict.

### ISSUE THREAD

**Issue by jphaneuf** [MRSD2018/GroundsBot#91]
UART from Jetson is fake news, need to use Jetson USB to Arduino.

Fuse holder is in the way. We can wiggle it in, better to move fuse holder next rev.

**Comment by zhenrychen** [comment]
Can we use longer pins into the arduino to generate clearance?

**Comment by joshuajbennett** [comment]
We fixed all the fake news.
