### ISSUE TITLE
Arduino Mega failed on GroundsBot

### ISSUE THREAD

**Issue by jphaneuf** [MRSD2018/GroundsBot#96]
Arduino Mega installed on GroundsBot was working, but failed during a reprogramming attempt (Board still mounted and connected to GroundsBot)

Mega wasn't completely bricked, power supplies ok, shows up as usb device, but can't be programmed

Haven't been able to root cause, but things to keep an eye out for:

- Powering Arduino from USB without rest of system powered on may do weird things, i.e. trying to feed other power systems from USB 5V
- We have an inadvertent chassis ground with our mounting. One metal standoff chewed solder mask on arduino and made contact with a ground plane, ends up connected to aluminum backplane, same happens on Jetson, bob's your uncle that's a chassis ground. Not sure this is a problem.

May have been a fluke, but want to keep an eye out

**Comment by joshuajbennett** [comment]
We fixed it!
